import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignedIn, SignedOut,SignInButton,  UserButton, useUser } from "@clerk/nextjs";

import { api } from "~/utils/api";
import SideBar from "~/pages/Sidebar"



const Home: NextPage = () => {

  const user = useUser();

  const {data} = api.posts.getAll.useQuery();


  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SideBar/>
      
      <main className="flex h-screen justify-center">
        <div className="h-full  border-orange-100 md:max-w-2xl">
          <div className="flex items-center p-4 border-b justify-center 
            bg-gradient-to-b from-orange-50 to-slate-200 text-slate-900 shadow-lg rounded-2xl">

          <SignedIn>
            <UserButton />
            <text className="text-stone-900 font-bold"> Personal Site</text>
          </SignedIn>
          <SignedOut>
            <SignInButton />
          </SignedOut>
          </div>
        <div>
          {data?.map((post)=>(
          <div key = {post.id}>{post.content}</div>
          ))}
        </div>
      </div>
      </main>
    </>
  );
};

export default Home;
